cheeaun/phanpy

src/components/avatar.css

12px border-radius made bot avatar icons round in boost carousel. 25% radius retains original shape in regular timeline and produces similar shape in the carousel.

fix squircle avatars in boost carousel

---

package-lock.json

This was done with https://github.com/jeslie0/npm-lockfile-fix
npm doesn't do the most stellar job when it comes to specifying the full integrity information (hashes and such)
inside the package-lock.json file. See more details at https://github.com/NixOS/nixpkgs/issues/261137
This makes building the package from a Nix context really hard (the issue above gives one such instance), and
this applies to your repo too :(
`npm-lockfile-fix` adds the hash of each package into the lock file. You can verify this all works (and is valid) by just doing
`npm install`.
Unfortunately this doesn't guarantee that `npm` won't mess it up again in the future, but I frankly have no idea
what to do until upstream issues get fixed :(

Update integrity information in `package-lock.json`

---

src/components/media.jsx

I've sent a PDF as an attachment to a Status, and phanpy tries to load it, but inside an <img> tag because that's the "default type". That fails.
In case of error, the code tries to change the url but it turns out to be exactly the same, so it tries again, and fails, and tries again, ad vitam eternam as fast as possible. This burns my CPU and even makes some calls to the same origin fail; the only recourse is to fresh-reload the app.
Non-image types don't seem to have this issue because there's no "retry with another url"
This little change makes sure we don't retry if it failed

Remote media: avoid never-ending loops if it won't work

---

src/components/compose.jsx

There is/was a convention that prepending a dot (.) before the @ makes the target user not mentioned. This is useful when you're using DMs for example and you want to talk about a third-party but don't want the third-party to get the message: putting the dot before doesn't send it to them.

Don't highlight mention when it's prepended by a dot

---

README.md

This PR adds a self-hosted phanpy deployment:
- **Domain**: `phanpy.gotosocial.social`
- **Contact account**: `@admin@gotosocial.social`
- **Service provider**: Cloudflare Pages
- I'll keep this deployment up to date with the upstream repository.

Add another self-hosted instance

---

src/app.css

When columns mode enabled, going to other pages will hide the columns, via this CSS:
```
#columns:has(~ .deck-container) {
display: block;
…
}
```
The display block rearranges the layout thus causing `<InView/>` component to trigger, causing infinite loop in its intersection observer, constantly loading the timeline.

[Hotfix] Infinite loop bug in intersection observer

---

README.md

Added phanpy.hear-me.social to the list of deployed sites in README.md
Domain: phanpy.hear-me.social
Contact account: @admin@hear-me.social
I'll keep the deployment up-to-date with the upstream repo

Update README.md to add hear-me.social

---

README.md

Adding fulda.social to the list of self-hosted instances.

Add another phanpy instance url

---

src/pages/notifications.css

Using Firefox for Android on a low-end phone, I notice that my notifications screen is very slow to scroll when I have 10+ notifications on one post.
When I remove this backdrop-filter style, the problem goes away - eyeball estimate is that scrolling gets 5x faster.
Edit: This resolves issue #416 .

(performance) Remove backdrop-filter blur and saturate effect from .account-sub-icons

---

src/components/modal.css

Using Firefox for Android on a low-end phone, when I check who interacted with a post and view someone's account, in the modal, it is _extremely_ slow to scroll - 500ms+ latency for scroll to start, and renders at ~5 FPS while scrolling.
For clarity, here is the screen I am referring to:
Most of this is due to the issue described in #430, and that diff greatly improves performance for this case as well. However, scrolling is still somewhat slow. Removing these backdrop-filter effects makes the scrolling significantly faster.
Testing on Firefox (desktop and mobile) and Chrome (desktop), I cannot notice a visual difference with and without the removed styles. I only tested this specific screen, and there are lots of other modals, so it may have made a visual difference elsewhere.

(performance) Remove backdrop-filter blur and saturate effects from modals

---

src/components/status.jsx

Expose the full content of preview text that might get truncated in their tooltips.
[Screencast from 2024-03-15](https://github.com/cheeaun/phanpy/assets/4251/2a383c56-9422-4b2f-82b1-2af5d90d1450)

Add tooltip for truncated preview text

---

src/components/timeline.jsx

Currently pressing `enter` opens the active status if the status _or_ any focusable child of the status is focused e.g. the avatar or a link. I think it should only open the post details when the post itself is focused.
Current behaviour (pressing enter when username focused opens post):
[enter_on_username_opens_post.webm](https://github.com/cheeaun/phanpy/assets/582896/b48ccccc-9a00-4c51-a128-74bade8548fc)
New behaviour (pressing enter when username focused opens profile):
[enter_on_username_opens_profile.webm](https://github.com/cheeaun/phanpy/assets/582896/0cde81fe-5bfe-41b8-b3d2-1075e248ec3b)

Fix `enter` keyboard shortcut on timeline

---

README.md

This pull request adds the phanpy.cz instance to the list of self-hosted instances. The instance is hosted by https://mamutovo.cz/@zdendys.
Community deployments
These are self-hosted by other wonderful folks.
...
phanpy.cz by https://mamutovo.cz/@zdendys
Note: Add yours by creating a pull request.

Added phanpy.cz to self-hosted instances

---

src/components/account-info.jsx

Currently, if you click the "Disable boosts" button, the toast would say "Boosts from user enabled." or click the "Enable boosts" button, it would say "Boosts from user disabled." 
This should be caused by a logic mistake and this PR fixes it.

fix: enable/disable boosts button logic

---

src/app.css

When an OS does not have “overlay” scrollbars, the `scroll` values of `overflow` lead to the empty scrollbars visible ([more details](https://blog.kizu.dev/never-use-overflow-scroll/)).
In the case of Phanpy, in its multicolumn view, this scrollbar eats from the available vertical space.

Fix overflow for the columns wrapper

---

src/components/shortcuts-settings.jsx

Shortcut syncing failed for me (`note` field on my account is empty). Noticed that `settingsJSON` wasn't defined in the `else` branch, so creating a new account note failed.

fix(shortcuts-settings): `settingsJSON` must be defined if note doesn't exist

---

src/utils/localeCode2Text.jsx

I wanted to try Phanpy, but only got a blank page, because `Intl.DisplayNames` can't handle some values that might appear in `navigator.languages`.
[As MDN says](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages):
> The [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) HTTP header in every HTTP request from the user's browser generally lists the same locales as the navigator.languages property, with decreasing q values (quality values).
My config includes `*;q=0.5` as the last value, which gives a `navigator.languages` like `['xx', 'xx', 'xx', 'xx', '*']`.
```js
new Intl.DisplayNames([..., '*'], {
type: 'language'
})
```
results in `RangeError: Incorrect locale information provided`.
So this proposed fix filters out any …

Filter out languages that aren't RFC5646-shaped

---

.gitattributes

GitHub uses [Linguist](https://github.com/github-linguist/linguist) for various features in repository pages, from displaying pull requests to calculating repository stats.
Sometimes, Linguist can use an hint in understanding how the project is structured, and that's done via [overrides](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md).
With this PR:
- `*.po` files are marked as `generated`, which means they start collapsed by default in pull requests like binary files and aren't counted in language stats;
- anything in `readme-assets/**` is marked as `documentation`, which for now only excludes the directory from language stats.
I think that this would make PRs easier to examine at a glance, as the significant content is highlighted, while not stopping anyone …

Configure linguist overrides for this repository

---

src/components/poll.jsx

Fixes #510.
---
[Your intuition](https://github.com/cheeaun/phanpy/issues/510#issuecomment-2066816279) was correct: that was the issue.
Sadly, a patch doesn't seem to have been merged upstream yet, so in the meantime, it seems to me that a better idea for handling multiple choice polls both on https://github.com/cheeaun/phanpy/labels/akkoma and the Mastodon API might be this.

Fix invalid vote counts on single choice polls on certain MastoAPI implementations

---

src/components/compose.jsx
src/locales/en.po

Fixes #778.
When editing a status, the `description` property on each attachment is read-only, so modifying it directly throws a `TypeError`.

Fix editing image descriptions

---

src/pages/status.jsx

This automatically redirects the user to the instance's login page if `PHANPY_DEFAULT_INSTANCE` is set.

Use the same logic as the main login button for the login tooltip in posts

---

src/utils/lang.js

If `navigator.languages` returns `['da', 'en-US', 'en']`, and the Danish language is not available, the user interface should be in English.
Currently it is shown in Norwegian, because only `'da'` is taken into account when deciding on the preferred language (and `match` selects `nb-NO` using the default `'best fit'` algorithm).
While the Norwegian and Danish languages are similar, I would argue that this is a bug, as `navigator.languages` cleary states that the fallback language should be English.
Another potential solution would be to pass `{ algorithm: 'lookup' }` to the `match` function. However, this might break some cases when a `'best fit'` approach would be appropriate (e.g. Swiss German falling back to German).
See https://helvede.net/@jwcph/113497955274343365.

fix(lang): respect fallback languages

---

README.md

added [phanpy.linuxusers.in](https://phanpy.linuxusers.in) to community deployments.

Added phanpy.linuxusers.in to community deployments

---

src/components/compose.jsx
src/locales/en.po

I decided to fix an issue that I had for a while: when trying to autocomplete a mention when inside a list, pressing `enter` closed the text-expander and created a new list, leaving the mention unfinished.
before | after
-|-
<video src="https://github.com/user-attachments/assets/1698deb8-3f6d-42f1-8f78-a58d1cdfba36" /> | <video src="https://github.com/user-attachments/assets/c3b0b3b4-388a-4940-bcfc-92c50d832c49" />
Did it by introducing a ref that is toggled on when the text-expander activates and off when it deactivates, and then checking this ref when doing the action on `enter`.

Fix text expander not working correctly in lists

---

src/utils/api.js

I often encounter timeouts ("Fetch aborted" error message) when uploading images on poor connections. This looks like the place where the global timeout is configured.

Increase global masto api timeout

---

src/components/compose.jsx

This commit fixes a bug where the composer would automatically create a new list item when pressing Enter during IME composition. The fix involves checking the  property of the keyboard event to prevent this behavior.

Fix: Prevent list auto-creation during IME composition
